### ISSUE TITLE
Assembly signing

### ISSUE THREAD

**Issue by ViceIce** [VisualOn/cssparser#1]
We ❤️ to have signed assemblies.

**Tasks**
- [ ] Create a `feature/signing` branch
- [ ] Create `CSSParser`  signing key
- [ ] Add signing config to [Directory.Build.props](https://github.com/VisualOn/cssparser/blob/dea630fed3692efcc8afafcc7be1c90de4ab87a8/Directory.Build.props) `PropertyGroup`
- [ ] Open a PR to master

```xml
<SignAssembly>true</SignAssembly>  
<AssemblyOriginatorKeyFile>$(MSBuildThisFileDirectory)CSSParser.snk</AssemblyOriginatorKeyFile>
 ```
